name: Generate Pacman Contribution SVG

on:
  schedule:
    - cron: "0 0 * * *" # Runs every day at midnight
  workflow_dispatch: # Allows you to run it manually

jobs:
  build:
    runs-on: ubuntu-latest
    name: Generate Pacman SVG
    steps:
      - uses: actions/checkout@v4

      - name: Generate Pacman SVG using local action
        uses: ./.github/actions/pacman-generator
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch_name: "output"
          commit_message: "feat: update pacman contribution graph"
