name: GitHub Actions Permission test

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js 20.x
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Verify Node.js installation
        run: node -v

      - name: Print Success Message
        run: echo "✅ SUCCESS: GitHub Actions workflow completed successfully."
